services:
  consumer-example-1:
    image: node
    command: [node, consumer.js]
    working_dir: /app
    volumes:
      - ./src/producer/:/app
  producer-example-1:
    image: node
    command: [node, index.js]
    working_dir: /app
    volumes:
      - ./src/producer/:/app
    environment:
      TOPIC: topic-test
  producer-example-2:
    image: node
    deploy:
      replicas: 2
    command: [node, index.js]
    working_dir: /app
    volumes:
      - ./src/producer/:/app
    environment:
      TOPIC: topic-2
  registry-example:
    image: node
    command: [node, schema-registry-example.js]
    working_dir: /app
    volumes:
      - ./src/producer/:/app
  